-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 21:11:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InvoicesCars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InvoicesCars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InvoicesCars` DEFAULT CHARACTER SET utf8 ;
USE `InvoicesCars` ;

-- -----------------------------------------------------
-- Table `InvoicesCars`.`CARS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvoicesCars`.`CARS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `VID` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `color`  VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InvoicesCars`.`SALES_PERSONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvoicesCars`.`SALES_PERSONS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `StaffID` VARCHAR(20) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `store` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `StaffID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InvoicesCars`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvoicesCars`.`CUSTOMERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMERID` VARCHAR(5) NULL,
  `name` VARCHAR(200) NOT NULL,
  `phone number` VARCHAR(20) NULL,
  `email` VARCHAR(80) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(40) NOT NULL,
  `state` VARCHAR(60) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idCUSTOMERS_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InvoicesCars`.`INVOICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvoicesCars`.`INVOICES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `InvoiceNumber` VARCHAR(45) NOT NULL,
  `Date` DATETIME NOT NULL,
  `Car` INT NOT NULL,
  `Customer` INT NOT NULL,
  `SalesPerson` INT NOT NULL,
   PRIMARY KEY (`ID`, `CARS_VIDid`, `CUSTOMERS_idCUSTOMERS`, `SALES_PERSONS_StaffID`),
  UNIQUE INDEX `idINVOICES_UNIQUE` (`ID` ASC) VISIBLE,
   CONSTRAINT `fk_INVOICES_CARS`
    FOREIGN KEY (`Car`)
    REFERENCES `InvoicesCars`.`CARS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVOICES_CUSTOMERS1`
    FOREIGN KEY (`Customer`)
    REFERENCES `InvoicesCars`.`CUSTOMERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVOICES_SALES_PERSONS1`
    FOREIGN KEY (`SalesPerson`)
    REFERENCES `InvoicesCars`.`SALES_PERSONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
